apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  #允许被单个节点以读写的模式进行挂载,local
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local: # local类型
    path: /run/desktop/mnt/host/e/docker/mount  #这是windows WSL 2 挂载路径写法
  nodeAffinity: # 这里就设置了节点亲和
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop # 这里我们指定节点，该节点有path路径
