apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-mysql-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: mysql-storage
  local: # local类型
    path: /run/desktop/mnt/host/e/docker/mount/mysql  #这是windows WSL 2 挂载路径写法
  nodeAffinity: # 这里就设置了节点亲和
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop # 这里我们使用node01节点，该节点有/data/vol1路径
