apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config-map
data:
  redis.conf: |
    bind 0.0.0.0
    port 6360
    # requirepass 123456
    appendonly yes
    protected-mode no
    dir /var/lib/redis