apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: redis
  name: redis
  #namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  serviceName: redis-svc
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis                               #容器名称
          image: redis:7.0                       #redis镜像
          imagePullPolicy: IfNotPresent             #镜像拉取策略
          command:                                  #定义容器的启动命令和参数
            - "redis-server"
          args:
            - "--masterauth"
            - "123456"
            - "--requirepass"
            - "123456"
            - "--protected-mode"
            - "no"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          ports:                                    #定义容器端口
            - name: redis-6379                        #为端口取个名称为http
              containerPort: 6379                     #容器端口
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
          volumeMounts:
            - name: "redis-data"                      #指定使用的卷名称,这里使用的是下面定义的pvc模板的名称
              mountPath: "/data"                      #redis数据的挂载点
              subPathExpr: $(POD_NAMESPACE)/$(POD_NAME)
              readOnly: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: "redis-conf"                        #挂载一个名为redis-conf的configMap卷,这个cm卷已经定义好了
          configMap:
            name: "redis-cm"
            defaultMode: 0755
            items:
              - key: "redis.conf"
                path: "redis.conf"
        - name: redis-data
          persistentVolumeClaim:
            claimName: local-pvc
  updateStrategy:
    type: RollingUpdate
