apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel-config
data:
  # 类属性键；每一个键都映射到一个简单的值
  ANNOUNCE_IP: "10.2.31.134"

  # 类文件键
  sentinel.conf: |
    protected-mode no
    port 26379
    dir "/tmp"
    sentinel monitor mymaster 10.2.31.134 6379 2
    sentinel auth-pass mymaster 123456
    sentinel down-after-milliseconds mymaster 30000
    sentinel parallel-syncs mymaster 1
    sentinel failover-timeout mymaster 180000
    sentinel deny-scripts-reconfig yes
  redis.conf: |
    port 6379