services:
  # 🟣 Loki：日志存储
  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./apm/loki/config.yaml:/etc/loki/config.yaml
      - loki-data:/loki
    networks:
      - net
  tempo:
    image: grafana/tempo:2.8.0
    container_name: tempo
    restart: unless-stopped
    ports:
      - "3200:3200"   # 查询服务
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    volumes:
      - ./apm/tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo   # 本地 traces 存储
    command: [ "-config.file=/etc/tempo.yaml" ]
    networks:
      - net
  # 🟢 Prometheus：用于监控 Vector 指标
  prometheus:
    image: prom/prometheus:v2.51.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./apm/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - net
  # 🟡 Grafana：日志展示界面
  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./apm/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - net
  # 🔵 Vector：日志采集器
  vector:
    image: timberio/vector:0.33.0-alpine
    container_name: vector
    restart: unless-stopped
    ports:
      - "8686:8686"  # Prometheus metrics
    volumes:
      - ./apm/vector/vector.yaml:/etc/vector/vector.yaml:ro
      - ../logs:/logs:ro
    networks:
      - net

volumes:
  grafana-storage:
  loki-data:
  tempo-data:

networks:
  net:
    external: true
    name: tfwk-net
