version: '3.3'
services:
  redis:
    image: redis:latest
    container_name: sg-redis
    restart: always
    networks:
      - sg-net
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  mysql:
    image: mysql:5.7
    container_name: sg-mysql
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DATASOURCE_PASSWORD}
      - TZ=Asia/Shanghai
    networks:
      - sg-net
    ports:
      - 3306:3306
    command: ["mysqld","--server_id=1","--log_bin","--innodb_ft_min_token_size=1","--ft_min_word_len=1","--ngram_token_size=1","--secure_file_priv="]
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: sg-nacos
    restart: always
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=sg-mysql
      - MYSQL_SERVICE_DB_NAME=nacos-db
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=${DATASOURCE_PASSWORD}
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    networks:
      - sg-net
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  redis-data:
  db-data:

networks:
  sg-net:
    external: true
    name: sg-net
