version: '3'
services:
  app-server:
    container_name: app-server
    image: nextcloud:fpm
    restart: always
    expose:
      - '80'
      - '9000'
    volumes:
      - app_data:/var/www/html
    networks:
      - sg-net
  only:
    container_name: only
    image: onlyoffice/documentserver:latest
    stdin_open: true
    restart: always
    stop_grace_period: 60s
    depends_on:
      - rabbitmq
    environment:
      - DB_TYPE=mysql
      - DB_HOST=sg-mysql
      - DB_PORT=3306
      - DB_NAME=onlyoffice-db
      - DB_USER=root
      - DB_PWD=root
      - AMQP_URI=amqp://guest:guest@rabbitmq
      #- JWT_ENABLED=true
      #- JWT_SECRET=secret
      #- JWT_HEADER=Authorization
      #- JWT_IN_BODY=true
    expose:
      - '80'
      - '443'
    ports:
      - 9001:80
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
    networks:
      - sg-net
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
      #- 443:443
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/ssl:/usr/local/ssl
      #- app_data:/var/www/html
    networks:
      - sg-net
  rabbitmq:
    image: rabbitmq:3.8.3-management
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - sg-net


volumes:
  document_data:
  document_log:
  app_data:
  rabbit_data:
  mysql_data:

networks:
  sg-net:
    external: true
    name: sg-net