services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: ptn
    restart: unless-stopped
    ports:
      - "9900:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - net

volumes:
  portainer_data:

networks:
  net:
    external: true
    name: my-net



