   FROM openjdk
    MAINTAINER sangang
    ENV FILEBEAT_VERSION=7.15.1 \
    FILEBEAT_SHA1=3fde7f5f5ea837140965a193bbb387c131c16d9c
   COPY filebeat.yml /filebeat.yml 
    RUN set -x && \
      apt-get update && \
      apt-get install -y wget && \
      wget https://download.elastic.co/beats/filebeat/filebeat-${FILEBEAT_VERSION}-x86_64.tar.gz -O /opt/filebeat.tar.gz && \
      cd /opt && \
      echo "${FILEBEAT_SHA1}  filebeat.tar.gz" | sha1sum -c - && \
      tar xzvf filebeat.tar.gz && \
      cd filebeat-* && \
      cp filebeat /bin && \
      cd /opt && \
      rm -rf filebeat* && \
      apt-get purge -y wget && \
      apt-get autoremove -y && \
      apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    ADD target/mq-0.0.1-SNAPSHOT.jar service.jar
    ENTRYPOINT ["java", "-jar", "/service.jar","--server.port=8080"]
    CMD [ "filebeat", "-e" ]
    EXPOSE 2222