version: '3'
services:
  mqapi:
    build:
      context: .
      args:
        FILEBEAT_VERSION: 7.15.1
        SERVICE_NAME: mq-0.0.1-SNAPSHOT
    container_name: sg-mq
    restart: always
    environment:
      TZ: Asia/Shanghai
    networks:
      - sg-net
    ports:
      - 8085:8080
    volumes:
      - type: bind
        source: ./filebeat.yml
        target: /filebeat.yml
        read_only: true
      - type: volume
        source: logs
        target: /app/logs

volumes:
  logs:

networks:
  sg-net:
    external:
      name: sg-net
