version: "3.4"

services:
  whisper-asr-webservice:
    # https://github.com/ahmetoner/whisper-asr-webservice
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: sg-whisper
    environment:
      - ASR_MODEL=base
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app/app
      - cache-pip:/root/.cache/pip
      - cache-poetry:/root/.cache/poetry
      - cache-whisper:/root/.cache/whisper

volumes:
  cache-pip:
  cache-poetry:
  cache-whisper:
  cache-faster-whisper:
