version: '3.2'
services:
  oracle19c:
    image: registry.cn-hangzhou.aliyuncs.com/zhuyijun/oracle:19c
    container_name: oracle19c
    restart: always
    ports:
      - "1521:1521"
    environment:
      ORACLE_SID: orcl
      ORACLE_PDB: orclpdb
      ORACLE_PWD: Jobs@666
      ORACLE_EDITION: standard
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - oracle19c_data:/opt/oracle/oradata
    networks:
      - my-net
  oracle9:
    image: roboxes/oracle9:latest
    container_name: oracle9
    restart: always
    ports:
      - "1522:1521"
    environment:
      ORACLE_SID: orcl
      ORACLE_PDB: orclpdb
      ORACLE_PWD: root
      ORACLE_EDITION: standard
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - oracle9_data:/opt/oracle/oradata
    networks:
      - my-net
  oracle11g:
    image: wnameless/oracle-xe-11g-r2
    container_name: oracle11g
    ports:
      - "1521:1521"   # Oracle 数据库端口
      - "8180:8080"   # APEX 管理界面端口（如启用）
    environment:
      - ORACLE_ALLOW_REMOTE=true  # 允许远程连接
    volumes:
      - oracle11g-data:/u01/app/oracle  # 持久化数据
    restart: unless-stopped
    networks:
      - my-net

volumes:
  oracle19c_data:
  oracle9_data:
  oracle11g-data:

networks:
  my-net:
    external: true
    name: my-net
