services:
  # 🟣 Loki：日志存储
  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./apm/loki/config.yaml:/etc/loki/config.yaml
      - loki-data:/loki
    networks:
      - net
  tempo:
    image: grafana/tempo:2.8.0
    container_name: tempo
    restart: unless-stopped
    ports:
      - "3200:3200"   # 查询服务
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    volumes:
      - ./apm/tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo   # 本地 traces 存储
    command: [ "-config.file=/etc/tempo.yaml" ]
    networks:
      - net
  # 🟢 Prometheus：用于监控 Vector 指标
  prometheus:
    image: prom/prometheus:v2.51.1
    container_name: prometheus
    restart: unless-stopped
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./apm/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - net
  # 🟡 Grafana：日志展示界面
  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./apm/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - net
  # 🔵 Vector：日志采集器
  vector:
    image: timberio/vector:0.33.0-alpine
    container_name: vector
    restart: unless-stopped
    ports:
      - "8686:8686"  # Prometheus metrics
    volumes:
      - ./apm/vector/vector.yaml:/etc/vector/vector.yaml:ro
      - ../logs:/logs:ro
    networks:
      - net
  mysql-exporter:
    image: prom/mysqld-exporter:v0.15.0
    container_name: mysql-exporter
    restart: unless-stopped
    ports:
      - "9104:9104"
    volumes:
      - ./apm/mysql-exporter/my.cnf:/etc/.my.cnf:ro
    command:
      - '--config.my-cnf=/etc/.my.cnf'
    networks:
      - net

  redis-exporter:
    image: oliver006/redis_exporter:v1.66.0
    container_name: redis-exporter
    restart: unless-stopped
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
    networks:
      - net
  k6: # 官方k6Prometheus Dashboard的ID:19665
    image: grafana/k6:latest
    container_name: k6
    depends_on:
      - prometheus
    volumes:
      - ./apm/k6-scripts:/scripts
    networks:
      - net
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
    entrypoint: >
      sh -c "k6 run --out experimental-prometheus-rw --out web-dashboard /scripts/regist.js"
    ports:
      - "5665:5665"

volumes:
  grafana-storage:
  loki-data:
  tempo-data:
  prometheus-data:

networks:
  net:
    external: true
    name: my-net
