version: '3.8'
services:
  libreoffice:
    image: libreoffice/online:latest
    ports:
      - "9990:9980"
    container_name: libreoffice
    privileged: true
    environment:
      username: admin
      password: 3g
      extra_params: --o:ssl.enable=false
      DONT_GEN_SSL_CERT: 1
    cap_add:
      - MKNOD
    restart:
      unless-stopped
    networks:
      - sg-net
  cb:
    image: collabora/code:latest
    ports:
      - "9980:9980"
    container_name: cb
    privileged: true
    #volumes:
      #- ./conf/coolwsd.xml:/etc/coolwsd/coolwsd.xml
    environment:
      username: admin
      password: 3g
      #domain: localhost
      aliasgroup1: https://172.20.10.9|127.0.0.1:443
      extra_params: --o:ssl.enable=false --o:ssl.termination=true
      #DONT_GEN_SSL_CERT: 1
    cap_add:
      - MKNOD
    restart:
      always
    networks:
      - sg-net
  web:
    image: nginx
    container_name: nginx
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/ssl:/usr/local/ssl
      - ../../file:/file
    restart:
      always
    networks:
      - sg-net


networks:
  sg-net:
    external: true
    name: sg-net
