version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: ng
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    networks:
      - ng


networks:
  ng:
    external: true
    name: my-net