version: '3.2'
services:
  oracle19c:
    image: registry.cn-hangzhou.aliyuncs.com/zhuyijun/oracle:19c
    container_name: oracle19c
    restart: always
    ports:
      - "1521:1521"
    environment:
      ORACLE_SID: orcl
      ORACLE_PDB: orclpdb
      ORACLE_PWD: Jobs@666
      ORACLE_EDITION: standard
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - oracle19c_data:/opt/oracle/oradata
    networks:
      - sg-net
  oracle9:
    image: roboxes/oracle9:latest
    container_name: oracle9
    restart: always
    ports:
      - "1522:1521"
    environment:
      ORACLE_SID: orcl
      ORACLE_PDB: orclpdb
      ORACLE_PWD: root
      ORACLE_EDITION: standard
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - oracle9_data:/opt/oracle/oradata
    networks:
      - sg-net

volumes:
  oracle19c_data:
  oracle9_data:

networks:
  sg-net:
    external: true
    name: sg-net
